workflow

diff --git a/.github/workflows/desktop-dart.yml b/.github/workflows/desktop-dart.yml
--- a/.github/workflows/desktop-dart.yml
+++ b/.github/workflows/desktop-dart.yml
@@ -20,6 +20,7 @@ jobs:
             platform: linux
             arch: x64
     runs-on: ${{ matrix.os }}
+    timeout-minutes: 30 # Set a timeout of 30 minutes for the job
     steps:
       - uses: actions/checkout@v4
       - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
@@ -27,26 +28,24 @@ jobs:
       - name: Install dependencies
         run: dart pub get
 
-      - name: Publish Windows
-        if: matrix.os == 'windows-latest'
-        run: dart compile exe .\bin\main.dart -o .\build\test_dart.exe
-        shell: pwsh
-      
-      - name: Publish Linux
-        if: matrix.os == 'ubuntu-latest'
-        run: dart compile exe .\bin\main.dart -o .\build\test_dart
+      - name: Build Application
+        run: |
+          if [ "${{ matrix.os }}" == "windows-latest" ]; then
+            dart compile exe .\bin\main.dart -o .\build\test_dart.exe
+          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
+            dart compile exe ./bin/main.dart -o ./build/test_dart
+          fi
         shell: bash
-      
-      - name: Zip artifact Windows
-        if: matrix.os == 'windows-latest'
-        run: Compress-Archive -Path ./build/* -DestinationPath ./test_dart_${{ matrix.platform }}_${{ matrix.arch }}.zip
-        shell: pwsh
-      
-      - name: Zip artifact Linux
-        if: matrix.os == 'ubuntu-latest'
-        run: zip -r ./test_dart_${{ matrix.platform }}_${{ matrix.arch }}.zip ./build
+
+      - name: Zip Artifact
+        run: |
+          if [ "${{ matrix.os }}" == "windows-latest" ]; then
+            Compress-Archive -Path ./build/* -DestinationPath ./test_dart_${{ matrix.platform }}_${{ matrix.arch }}.zip
+          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
+            zip -r ./test_dart_${{ matrix.platform }}_${{ matrix.arch }}.zip ./build
+          fi
         shell: bash
-      
+
       - name: Upload artifact
         uses: actions/upload-artifact@v3
         with:
@@ -58,27 +57,27 @@ jobs:
     runs-on: ubuntu-latest
     if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
-    - name: Download artifacts
-      uses: actions/download-artifact@v3
-    - name: Validate artifacts
-      run: |
-        for file in ./*/*.zip; do
-          if ! unzip -t "$file" > /dev/null; then
-            echo "Error: $file is not a valid zip file"
-            exit 1
-          fi
-        done
-    - name: Create Release
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      run: |
-        assets=""
-        for file in ./*/*.zip; do
-          assets="$assets $file"
-        done
-        gh release create ${{ github.ref_name }} \
-          --title "Release ${{ github.ref_name }}" \
-          --generate-notes \
-          $assets
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Download artifacts
+        uses: actions/download-artifact@v3
+      - name: Validate artifacts
+        run: |
+          for file in ./*.zip; do
+            if ! unzip -t "$file" > /dev/null; then
+              echo "Error: $file is not a valid zip file"
+              exit 1
+            fi
+          done
+      - name: Create Release
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          assets=""
+          for file in ./*.zip; do
+            assets="$assets $file"
+          done
+          gh release create ${{ github.ref_name }} \
+            --title "Release ${{ github.ref_name }}" \
+            --generate-notes \
+            $assets || { echo "Error: Failed to create release"; exit 1; }
